
- name: Extract mount_sizes
  block:
    - ansible.builtin.set_fact:
        lvm_var: "{{  ansible_facts.lvm | ansible.utils.remove_keys(target=['free_g']) }}"
- name: Expected LVM
  debug:
    msg: "{{ disk.lvm | to_nice_yaml(indent=2) }}"
    verbosity: 1

- name: Actual LVM
  debug:
    msg: "{{ lvm_var | to_nice_yaml(indent=2) }}"
    verbosity: 1
- assert:
    that:
      - disk.lvm == lvm_var
    fail_msg: "CH (LVM): FAIL"
    success_msg: "CH (LVM): PASS"
