- name: Read the contents of /etc/sssd/sssd.conf
  ansible.builtin.slurp:
    src: /etc/sssd/sssd.conf
  register: sssd_content
  ignore_errors: true

- name: Convert sssd.conf content from base64
  ansible.builtin.set_fact:
    sssd_text: "{{ sssd_content['content'] | b64decode }}"
  when: sssd_content is defined and not sssd_content.failed

- name: Extract and clean simple_allow_users from sssd.conf
  ansible.builtin.set_fact:
    simple_allow_users: "{{ (sssd_text | regex_findall('simple_allow_users\\s*=\\s*([^\\n]+)') | first | split('=') | last | split(',') | map('trim') | list) }}"

- name: Extract and clean simple_allow_groups from sssd.conf
  ansible.builtin.set_fact:
    simple_allow_groups: "{{ (sssd_text | regex_findall('simple_allow_groups\\s*=\\s*([^\\n]+)') | first | split('=') | last | split(',') | map('trim') | list) }}"
  when: sssd_text is defined

- name: Check sssd_list against simple_allow_users and simple_allow_groups
  ansible.builtin.set_fact:
    users_missing: "{{ sssd_list | difference(simple_allow_users + simple_allow_groups) }}"
    extra_users: "{{ (simple_allow_users + simple_allow_groups) | difference(sssd_list) }}"

- name: Display discrepancies
  ansible.builtin.debug:
    msg: "SSSD configuration mismatch detected: Extra Users/Groups not in sssd_list: {{ extra_users }} | Users/Groups missing from SSSD configuration: {{ users_missing }}"
    verbosity: 1

- name: Assert no discrepancies in SSSD configuration
  ansible.builtin.assert:
    that:
      - users_missing | length == 0
      - extra_users | length == 0
    fail_msg: "SSSD configuration mismatch detected: Extra Users/Groups not in sssd_list: {{ extra_users }} | Users/Groups missing from SSSD configuration: {{ users_missing }}"
    success_msg: "SSSD configuration matches expected sssd_list."