- set_fact: # Todo: Check groups[group.name] exists
    flat_access_list: "{{ _flat_access_list | from_yaml }}"
  vars:
    _flat_access_list: |-
      access_list:
      {% for group in access_list.groups -%}
      {% for port in group.ports %}
      {% for single in groups[group.name] %}
      - {name: {{ single }}, port: {{ port }}}
      {% endfor %}
      {% endfor %}
      {% endfor %}
      {% for single in access_list.singles %}
      {% for port in single.ports %}
      - {name: {{ single.name }}, port: {{ port }}}
      {% endfor %}
      {% endfor %}

- debug:
    msg: "{{flat_access_list}}"
    verbosity: 1

- name: Check group access lists
  access_check:
    dst: "{{ access_item.name }}"
    port: "{{ access_item.port }}"
    timeout: "{{ timeout_value }}"
    failed_on: "{{ failed_on }}"
  with_items: "{{ flat_access_list.access_list }}"
  loop_control:
    loop_var: access_item
  register: access_check_result

- name: DENIED Remote access list (check LOCALHOST Denied list also)
  debug:
    msg: "{{ access_check_result | community.general.json_query('results[?access==`false`].access_item') | to_nice_yaml  }}"
  changed_when: access_check_result | community.general.json_query('results[?access==`false`].access_item')|length>0
