- name: Copy the public certificate to the system certificates directory
  ansible.builtin.copy:
    src: "{{ public_cert }}"
    dest: "/usr/local/share/ca-certificates/{{ public_cert }}"
    owner: "{{ cert_permissions_owner }}"
    group: "{{ cert_permissions_group }}"
    mode: "{{ cert_permissions_mode }}"
  register: copy_cert_result

- name: Update the CA certificates to trust the new certificate
  ansible.builtin.command:
    cmd: update-ca-certificates
  register: update_ca_cert
  changed_when: "'1 added' in update_ca_cert.stdout"
  when: copy_cert_result.changed
